spring.application.name=budgeting

spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3307/transaction
spring.datasource.username=app
spring.datasource.password=app
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.chat.options.model=gpt-4o-mini
#spring.ai.openai.chat.options.temperature=0.8

spring.ai.model.audio.transcription=openai

spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.language=pt
spring.ai.openai.audio.transcription.options.temperature=0
spring.ai.openai.audio.transcription.options.response-format=text
spring.ai.openai.audio.transcription.options.prompt=Audio em português brasileiro. \
  Audio contem descrição de gastos financeiros. \
  As frases geralmente contem: \
  - um valor em reais (números + "reais"); \
  - uma ação (gastei, paguei, comprei); \
  - um local ou estabelecimento (mercado, padaria, restaurante, loja, etc.).

spring.ai.model.audio.speech=openai
spring.ai.openai.audio.speech.options.model=gpt-4o-mini-tts
spring.ai.openai.audio.speech.options.voice=nova
spring.ai.openai.audio.speech.options.speed=1.2
spring.ai.openai.audio.speech.options.response-format=mp3

logging.level.org.springframework.ai=debug